# Generated by Django 5.0.6 on 2024-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('schedule', models.TextField()),
                ('testimonials', models.TextField()),
                ('faq', models.TextField()),
            ],
        ),
    ]
